### ISSUE TITLE
handle map[*A]B better

### ISSUE THREAD

**Issue by thockin** [davecgh/go-spew#30]
I have a `map[*MyStruct]OtherThing`.  Even with SortKeys set to true, the map ordering is non-deterministic (pointers, duh).  I wonder if we could do something more heavyweight but deterministic when *MyStruct does not have a String() method?  Maybe a new config option like `SpewKeys` which would apply the same spew conversion to each map key, then sort the resulting strings.

I understand it's a pretty niche case, but  it would be useful in our generic "hash object" logic.

Alternatively, some way to get an error for a non-deterministic spew?

**Comment by thockin** [comment]
Actually, it's worse than this - even maps with structs as keys are broken.

The docs say `sorted according to the reflect.Value.String()` which (incorrectly) made me think that I could define String() for my struct and it would work.  This is not the case.  Instrumenting the sort code I get a bunch of sort operations for "MyStruct Value", since it is a map[MyStruct].  This obviously produces random sort order because map is random order.

Can we do better?  You already handle testing for error and Stringer in other places...

**Comment by thockin** [comment]
Quick hacks to convert to stringer in valueSorter.Less fixes my use case...

**Comment by thockin** [comment]
FWIW I can (try to) implement if you're open to something here.

**Comment by thockin** [comment]
ping?  I just want to know if you're open to a fix here or not - if not I have to commit my own workarounds and caveats to our tree.

**Comment by davecgh** [comment]
@thockin: Sorry for the delay.  I've been deep in btcd/wallet stuff.  I don't mind having an option for it.

**Comment by thockin** [comment]
Thanks.  I'll think about a change and see if I can get you a PR.

**Comment by davecgh** [comment]
Implemented by #31.
