### ISSUE TITLE
Feature request: json output

### ISSUE THREAD

**Issue by rvm2015** [davecgh/go-spew#40]
It would be very helpful if there was something like spew.SdumpJSON or a flag on dump methods to kick out our output as JSON.

The specific use case I have in mind is if there's an exception and I want to kick out an object into my logging stream which would then get picked up and shipped off to an ELK stack (Kibana and soon Sumologic can automatically parse json fields).

**Comment by davecgh** [comment]
This isn't sound like something I'd like to add to the package.  I understand that might be some use in niche cases, but it's not what this package was designed for and I'd prefer not to have it feature creep.

You are free to fork it and add the functionality for your particular use case.
