### ISSUE TITLE
blog post link fails HSTS with chrome

### ISSUE THREAD

**Issue by mmlb** [davecgh/go-spew#41]

**Comment by davecgh** [comment]
Alright, thanks for the heads up.  I'll probably just convert it to markdown and put it in the repo.

**Comment by davecgh** [comment]
Fixed by #51.

**Comment by shurcooL** [comment]
You probably meant that it's fixed by #50.

**Comment by davecgh** [comment]
Correct.  Thanks.  I edited the comment accordingly.
