### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [davecgh/go-spew#43]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for go-spew and versioning would help Debian keep up with development.

**Comment by benma** [comment]
Please do this, it would help a lot.

**Comment by jredville** [comment]
This is also useful for anyone using Glide to manage their dependencies. Thank you

**Comment by davecgh** [comment]
I'll tag this right after I get the two PRs in.

**Comment by davecgh** [comment]
Done.
