### ISSUE TITLE
unsafe on GAE

### ISSUE THREAD

**Issue by pjebs** [davecgh/go-spew#62]
For environments where unsafe isn't allowed,
will this package follow pointers and print out their concrete value?

**Comment by shurcooL** [comment]
There's a section in the README about this, but it doesn't seem to go into details:

https://github.com/davecgh/go-spew#unsafe-package-dependency

> however it also supports a "limited" mode which allows it to work in environments where the unsafe package is not available.

**Comment by pjebs** [comment]
I tested this on GAE. I can confirm that this package **DOES** follow pointers and prints out its concrete value.

@davecgh What exactly are the reduced features in "limited" mode then?
