### ISSUE TITLE
How to dump the contents of a pointer?

### ISSUE THREAD

**Issue by corpix** [davecgh/go-spew#82]
If you `spew.Dump(some-pointer)` then you will see something like this:

``` console
(*lua.LTable)(0xc4202f1ec0)(table: 0xc4202f1ec0)
```

It is unclear, how to make it dump the whole structure and not just type name + address?

**Comment by davecgh** [comment]
It will do so automatically unless that type also has a stringer on it.  In that case you can set the `spew.Config.DisablePoinerMethods = true` to avoid invoking them.
