### ISSUE TITLE
Ignore Stringer() interface

### ISSUE THREAD

**Issue by pjebs** [davecgh/go-spew#89]
Is there somewhere to configure Spew so that `Sdump` ignores `Stringer` interface.

**Comment by jrick** [comment]
It may be reasonable to avoid usage of Stringer by default.  [GoStringer](https://godoc.org/fmt#GoStringer) would be a more appropriate choice.

**Comment by millerlogic** [comment]
```go
spew.Config.DisableMethods = true
```
You can also make your own ```ConfigState``` and call ```Sdump``` on it.
